name: CODESYS Installation Setup

on:
  push:
    branches:
      - main
      - cache-*
      - update-*
    paths-ignore:
      - 'README.md'

jobs:
  installer:
    uses: ./.github/workflows/test-install-installer.yml

  versions:
    uses: ./.github/workflows/test-install-versions.yml

  addons:
    uses: ./.github/workflows/test-install-addons.yml

  cache:
    uses: ./.github/workflows/test-install-cache.yml

  edge:
    uses: ./.github/workflows/test-install-edge.yml
